apiVersion: v1
kind: Service
metadata:
  name: envoy-admin-console
  namespace: app-tier
spec:
  type: NodePort
  selector:
    app: aspen-mesh-controlplane
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 15000
      targetPort: 15000
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30009
