---
# Service entry for external mTLS enabled service 
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
 name: myapp-se
 namespace: foobar
spec:
 hosts:
 - myapp.com
 location: MESH_EXTERNAL
 ports:
 - number: 443
   name: tls
   protocol: TLS
 resolution: DNS
 endpoints:
 - address: ec2-3-7-183-124.ap-south-1.compute.amazonaws.com
   locality: green
   ports:
     tls: 443
# Virtual Service for routing traffic from app-container to Istio-sidecar-proxy 
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mtls-vs
  namespace: foobar
spec:
  hosts:
  - myapp.com
  http:
  - route:
    - destination:
        host: myapp.com
        port:
          number: 443

---
# Destination rule for using custom certs attached as secrets/configmap on istio-sidecar-proxy 
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: mtls-dr
  namespace: foobar
spec:
  host: myapp.com
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: MUTUAL
        clientCertificate: /etc/certs/client.crt
        privateKey: /etc/certs/client.key
        caCertificates: /etc/certs/ca.crt
---
