apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: version1-routing-vs
  namespace: app-tier
spec:
  hosts:
  - myapp.com
  http:
  - name: "app-v1-route"  
    route:
    - destination:
        host: app-tier-svc.app-tier.svc.cluster.local
        subset: v1
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: app-dr
  namespace: app-tier
spec:
  host: app-tier-svc.app-tier.svc.cluster.local 
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
