## Test-command curl --header "user: ram" web-tier-svc.web-tier.svc.cluster.local
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: identity-routing-vs
  namespace: app-tier
spec:
  hosts:
  - app-tier-svc.app-tier.svc.cluster.local
  http:
  - match:
    - headers:
        user:
          exact: internal
    route:
    - destination:
        host: app-tier-svc.app-tier.svc.cluster.local
        subset: v2
  - route:
    - destination:
        host: app-tier-svc.app-tier.svc.cluster.local
        subset: v1
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: app-destination
  namespace: app-tier
spec:
  host: app-tier-svc.app-tier.svc.cluster.local 
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
