apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app-tier-delay-v1
  namespace: app-tier
spec:
  hosts:
  - app-tier-svc.app-tier.svc.cluster.local
  http:
  - fault:
      delay:
        fixedDelay: 7s
        percentage:
           value: 50
    route:
    - destination:
        host: app-tier-svc.app-tier.svc.cluster.local
        subset: v1
  - route:
    - destination:
        host: app-tier-svc.app-tier.svc.cluster.local
        subset: v2
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: app-dr
  namespace: app-tier
spec:
  host: app-tier-svc.app-tier.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2


