#for i in {1..7}; do time curl web-tier-svc.web-tier.svc.cluster.local; done
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vs-traffic-shifting
  namespace: app-tier
spec:
  hosts:
    - myapp.com
  http:
  - route:
    - destination:
        host: app-tier-svc.app-tier.svc.cluster.local
        subset: v1
      weight: 50
    - destination:
        host: app-tier-svc.app-tier.svc.cluster.local
        subset: v2
      weight: 50
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: app-dr
  namespace: app-tier
spec:
  host: app-tier-svc.app-tier.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v1
    labels:
      version: v2
