## To test run this on test-tier $for i in {1..9}; do curl web-tier-svc.web-tier.svc.cluster.local -I; done
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app-tier-abort-500-v1
  namespace: app-tier
spec:
  hosts:
  - app-tier-svc.app-tier.svc.cluster.local
  http:
  - fault:
      abort:
        httpStatus: 500
        percentage:
           value: 50
    route:
    - destination:
        host: app-tier-svc.app-tier.svc.cluster.local
        subset: v2
  - route:
    - destination:
        host: app-tier-svc.app-tier.svc.cluster.local
        subset: v1
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: app-dr
  namespace: app-tier
spec:
  host: app-tier-svc.app-tier.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
