---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-tier-deployment-v2
  namespace: app-tier
  labels:
    app: app-tier
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-tier
      version: v2
  template:
    metadata:
      labels:
        app: app-tier
        version: v2
    spec:
      containers:
      - name: app-tier-v2
        image: docker.io/giriraj789/informatica:v2
        ports:
        - containerPort: 80
          name: http-v2
