##kubectl create ns test-tier
##kubectl label ns test-tier istio-injection=enabled 
##kubectl get ns -L istio-injection
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-tier
  namespace: test-tier
  labels:
    app: test-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-tier
  template:
    metadata:
      labels:
        app: test-tier
    spec:
      containers:
      - name: test-tier
        image: giriraj789/tester:v1
