apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    istio-injection: disable
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: test
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: giriraj789/tester:v1
