## test use $seq 1 200 | xargs -n1 -P10  curl -I "http://web-tier-svc.web-tier.svc.cluster.local"

# The code represents the configuration for a VirtualService and a DestinationRule in Istio service mesh. 
# The VirtualService specifies routing rules for an application running in the "app-tier" namespace, 
# and the DestinationRule configures circuit breaking and outlier detection for the same application. 
# The configuration sets a limit on the number of requests per connection, number of connections, 
# and allows the system to automatically eject unhealthy instances from the pool of healthy instances.


apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: circuit-break-vs
  namespace: app-tier
spec:
  hosts:
  - app-tier-svc.app-tier.svc.cluster.local
  http:
  - name: "app-route"  
    route:
    - destination:
        host: app-tier-svc.app-tier.svc.cluster.local
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: circuit-breaking-dr
  namespace: app-tier
spec:
  host: app-tier-svc.app-tier.svc.cluster.local
  trafficPolicy:
    connectionPool:
      http:
        maxRequestsPerConnection: 1
        http2MaxRequests: 1
      tcp:
        maxConnections: 1
    outlierDetection:
      baseEjectionTime: 3m
      consecutive5xxErrors: 1
      interval: 1ms
      maxEjectionPercent: 100
